# Generated by Django 3.2.3 on 2021-05-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_genre',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
